version: 2
updates:
  - package-ecosystem: npm
    directory: /src/Asm.AmCom.Web
    schedule:
      interval: weekly
      timezone: "Australia/Brisbane"
      day: tuesday
      time: "06:00"
    reviewers:
      - andrewmcLachlan
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      timezone: "Australia/Brisbane"
      day: tuesday
      time: "06:00"
    reviewers:
      - andrewmcLachlan

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: "Australia/Brisbane"
      day: tuesday
      time: "06:00"
    reviewers:
      - andrewmcLachlan