//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asm.AmCom.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asm.AmCom.Web.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 - Bad Request.
        /// </summary>
        public static string Error400Description {
            get {
                return ResourceManager.GetString("Error400Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry, the address you entered is not well formed.
        /// </summary>
        public static string Error400FriendlyMessage {
            get {
                return ResourceManager.GetString("Error400FriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - Not Found.
        /// </summary>
        public static string Error404Description {
            get {
                return ResourceManager.GetString("Error404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry but the page you were looking for could not be found..
        /// </summary>
        public static string Error404FriendlyMessage {
            get {
                return ResourceManager.GetString("Error404FriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 - Server Error.
        /// </summary>
        public static string Error500Descripion {
            get {
                return ResourceManager.GetString("Error500Descripion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry but there has been a problem with the page you were trying to access..
        /// </summary>
        public static string Error500FriendlyMessage {
            get {
                return ResourceManager.GetString("Error500FriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry but there has been a problem with the page you were trying to access..
        /// </summary>
        public static string GenericFriendlyMessage {
            get {
                return ResourceManager.GetString("GenericFriendlyMessage", resourceCulture);
            }
        }
    }
}
